# ---------------------------------------------------------------------------------------------------------------------
# CLUSTER OUTPUTS
# ---------------------------------------------------------------------------------------------------------------------

output "cluster_id" {
  description = "The name/id of the EKS cluster"
  value       = aws_eks_cluster.main.id
}

output "cluster_name" {
  description = "The name of the EKS cluster"
  value       = aws_eks_cluster.main.name
}

output "cluster_arn" {
  description = "The Amazon Resource Name (ARN) of the cluster"
  value       = aws_eks_cluster.main.arn
}

output "cluster_endpoint" {
  description = "Endpoint for your Kubernetes API server"
  value       = aws_eks_cluster.main.endpoint
}

output "cluster_version" {
  description = "The Kubernetes server version for the cluster"
  value       = aws_eks_cluster.main.version
}

output "cluster_platform_version" {
  description = "The platform version for the cluster"
  value       = aws_eks_cluster.main.platform_version
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = aws_eks_cluster.main.certificate_authority[0].data
}

# ---------------------------------------------------------------------------------------------------------------------
# SECURITY OUTPUTS
# ---------------------------------------------------------------------------------------------------------------------

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = aws_security_group.eks_cluster.id
}

output "cluster_iam_role_arn" {
  description = "IAM role ARN of the EKS cluster"
  value       = aws_iam_role.eks_cluster.arn
}

output "cluster_iam_role_name" {
  description = "IAM role name of the EKS cluster"
  value       = aws_iam_role.eks_cluster.name
}

# ---------------------------------------------------------------------------------------------------------------------
# OIDC OUTPUTS
# ---------------------------------------------------------------------------------------------------------------------

output "oidc_provider_arn" {
  description = "ARN of the OIDC Provider for EKS"
  value       = var.enable_irsa ? aws_iam_openid_connect_provider.eks[0].arn : null
}

output "oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = try(aws_eks_cluster.main.identity[0].oidc[0].issuer, null)
}

# ---------------------------------------------------------------------------------------------------------------------
# ADDON OUTPUTS
# ---------------------------------------------------------------------------------------------------------------------

output "eks_addons" {
  description = "Map of enabled EKS add-ons and their properties"
  value       = aws_eks_addon.main
}

# ---------------------------------------------------------------------------------------------------------------------
# USEFUL FOR KUBECTL CONFIGURATION
# ---------------------------------------------------------------------------------------------------------------------

output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value = {
    cluster_name = aws_eks_cluster.main.id
    endpoint     = aws_eks_cluster.main.endpoint
    ca_data      = aws_eks_cluster.main.certificate_authority[0].data
    region       = data.aws_region.current.name
  }
}