{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-example.serviceAccountName" . }}
  labels:
    {{- include "node-example.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.irsaRoleArn }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.irsaRoleArn }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
